
<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/resume.css') ?>

<?php $this->headTitle("Ben Wanninger"); ?>

<div class="container" id="resume">
	<h1>Benjamin Wanninger</h1>
    <h4><a href="mailto:ben@benwann.net">ben ( at ) benwann.net</a> - 608-772-9722</h4>
    <h4>Chicago, IL<h4>
  <div class="row">
  	<div class="col-md-8">
  	  	<div id="interest">
	      <h3>Interest</h3>
	      <p>A web developer that is passionate about architecting ideas that help optimize and simplify processes through automation and intuitive design. A self-motivator that never tires of learning through challenges, and always welcomes the opportunity to improve upon the current skillset.  </p>
  		</div>
  		<div class="row" id ="skills">
  			<h3>Skills</h3>
  			<div class="col-md-3">
  				<h4><u>Proficient</u></h4>
  				<ul>
  					<li>PHP</li>
  					<li>MVC</li>
  					<li>MySQL</li>
  					<li>Agile Development</li>
  					<li>HTML5</li>
  					<li>CSS</li>
  					<li>Bootstrap</li>
  					<li>jQuery</li>
  				</ul>
  			</div>
  			<div class="col-md-3">
  				<h4><u>Competent</u></h4>
  				<ul>
  					<li>Ruby</li>
  					<li>Rails</li>
  					<li>Zend Framework</li>
  					<li>LAMP</li>
  					<li>Javascript</li>
  					<li>Unit Testing & TDD</li>
  					<li>BDD</li>
  					<li>Cucumber</li>
  				</ul>
  			</div>
  		</div>
  		<div id="experience">
	      <h3>Experience</h3>
	      <p><b>Freelance Web Design</b> - October 2011- Current</p>
	      <p>During this time I taught myself PHP/MySQL/Ruby/Rails while designing and coding side projects. Created simple apps that allowed daily tasks to be completed more quickly and efficiently.  Eventually using MVC architecture with Zend 2 and CodeIgniter frameworks to strengthen my knowledge of OOP</p>
	      <p><b>Betterfly</b> - July 2012 - October 2013</p>
	      <p>Programmatically solved day-to-day tasks by implementing apps to parse the data necessary for analyzing the community’s priorities. Worked closely with an Agile development team as the community manager. Acted as a liaison between the community of 60 thousand professionals and the CTO. Assisted in QA testing of a complete site redesign. Contributed to UX design through A/B testing that increased conversion by 100%.</p>
  		</div>
  		<div id="projects">
	      <h3>Projects</h3>
	      <p><b>Health Tracker</b> </p>
	      <p>Health </p>
	      <p><b>Daily Sketch</b></p>
	      <p></p>
  		</div>
    </div> 
    <div class="col-md-2" id="sideProfile">
     <img src="/img/BenjaminWanningerC.jpg" id="resumePicture" >
     <p> Be the fuckin man</p>
    </div>
  </div>
</div>


