<!--recieves Drawings which is an array of Drawing Objects that 
	are returned from the fetchall() db query 
    
-->

<h1>My Gallery</h1>

<?php //$drawings = $this->drawings;?>

<div id="galleryBody">
<?php foreach ($drawings as $drawing) : ?>
	<?php //echo var_dump($drawing) ?>
	<?php $link = $this->url('album',array('action'=>'view','id'=>$drawing->id)); ?>
	<?php echo '<a href="'.$link.'"><img class="albumThumb" border="0" src="/img/upload/'.$this->escapeHtml($drawing->fileName).'" alt="'.$this->escapeHtml($drawing->title).'"></a>';?>
<?php endforeach; ?>
</div>
 <?php //echo $_SERVER['REQUEST_TIME'] ?> 
