<?php

$form->prepare(); // The correct enctype is set here ?>
<?php echo $this->form()->openTag($form); ?>

    <div class="form-element">
    <?php
    $elem = $form->get('text');
    $elem->setLabelAttributes(array('class' => 'control-label'));
    $errors = $elem->getMessages();
    $errorClass = (!empty($errors)) ? ' error' : '';
    ?>
    <div class="control-group<?php echo $errorClass ?>">
        <?php echo $this->formLabel($elem); ?>
        <div class="controls">
            <?php echo $this->formText($elem); ?>
        </div>
    </div>


        <?php $fileElement = $form->get('image-file'); ?>
        <?php echo $this->formLabel($fileElement); ?>
        <?php echo $this->formFile($fileElement); ?>
        <?php echo $this->formElementErrors($fileElement); ?>
    </div>
    </br>
    <button>Upload</button>

<?php echo $this->form()->closeTag(); ?>


<?php if(isset($this->data))
	{
		echo $this->data["image-file"]["tmp_name"];

		//
	}
	else 
	{
		echo "Please fill in the Title and select Image to Upload";

		//echo file_get_contents('/img/upload/sphere.jpg');
		//echo '<img src="/img/upload/sphere.jpg">';
	} ?>

<?php //echo "<h3>status Dump</h3>"; echo var_dump($this->status); ?>
<?php //echo "<h3>Data Dump</h3>"; echo var_dump($this->data); ?>