<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Daily Sketch'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/Chart.min.css')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div id="wrap">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Ted\'s Daily Art') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a></li>
                        <li><a href="<?php echo $this->url('album',array('action'=>'gallery')) ?>"><?php echo $this->translate('Gallery') ?></a></li>
                        <li><a href="<?php echo $this->url('album',array('action'=>'upload-form')) ?>"><?php echo $this->translate('Image Upload') ?></a></li>
                        <li><a href="<?php echo $this->url('album',array('action'=>'view')) ?>"><?php echo $this->translate('View') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                      <!-- <li><a href="<?php echo $this->url('album',array('action'=>'login')) ?>">Login</a></li> -->
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="<?php echo $this->url('album',array('action'=>'login')) ?>">Login</a></li>
                          <li><a href="<?php echo $this->url('album',array('action'=>'logout')) ?>">Logout</a></li>
                        </ul>
                      </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="main-content">
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        </div> <!-- /main-content -->
        <div id="footer">
            <div class="container">
                <p class="text-muted credit">&copy; 2005 - <?php echo date('Y') ?> by Ben Dubbs LLC. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </div>
        </div> <!-- Wrap -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
