<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to Ben\'s Portfolio'))?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have stumbled upon Ben\'s project page.')) ?></p>
    
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Daily Sketch') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate("Here you can follow along on Ted's journey to becoming a great artist. If you're inspired to join him, you can ask to create your own account and start adding your daily sketches.") ?></p>
                <p><a class="btn btn-primary pull-right" href="http://www.benwann.net/album/gallery"><?php echo $this->translate("Ted's Daily Sketch") ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Health Tracker') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('The Health Tracker is a simple tool that allows you to track your food intake and mood. It also allows you to set weightloss and nutrition goals while tracking your progress.') ?></p>
                <p><a class="btn btn-primary pull-right" href="http://www.benwann.net/tracker" ><?php echo $this->translate('Try The Health Tracker') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Contact Me') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('If you need any help or support while using any of my apps, feel free to shoot me an email with any questions or suggestions that you may have. Enjoy!') ?></p>
                <p><a class="btn btn-primary pull-right" href="mailto:ben.wanninger@gmail.com""><?php echo $this->translate('Contact Me') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
