<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sBen\'s Portfolio%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have stumbled upon Ted\'s glorious getting-awesome-at-art page. You can see view his daily sketches %shere%s, and follow his journey to total awesomeness.'), '<a href="album">', '</a>') ?></p>
    
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Daily Sketch') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate("Here you can follow along Ted's journey to becoming a better artist. If you're inspired to join him, you can create your own account and start adding your daily sketches.") ?></p>
                <p><a class="btn btn-success pull-right" href="http://www.benwann.net/album/gallery"><?php echo $this->translate("Ted's Daily Sketch") ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Health Tracker') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('The Health Tracker is a simple tool that allows you to track your food intake and mood. It allows you to set goals weightloss and nutrition goals and see your progress.') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Try The Health Tracker') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Contact Me') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('If you need any help or support while using any of my apps, feel free to shoot me an email with any questions or suggestions that you may have. Enjoy!') ?></p>
                <p><a class="btn btn-success pull-right" href="mailto:ben.wanninger@gmail.com""><?php echo $this->translate('Contact Me') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
