<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/typeahead.js-bootstrap.css')
  ->prependStylesheet($this->basePath() . '/css/healthTracker.css') ?>

<div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h2> <?=$name?>'s Health Tracker</h2>
            <p>This is the beginnings of a health tracker. You can now log your current mood, and food intake. Soon you will be able to add goals, and track input over time.</p>
          </div>
          <div class="row">
            <?php
          $foodForm->setAttribute('action', $this->url('tracker', array('action' => 'add')));
          $foodForm->prepare();
          echo $this->form()->openTag($foodForm);
          echo $this->formCollection($foodForm);
          echo $this->form()->closeTag();
            ?>
          </div><!--/row-->
        </div><!--/span-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
            


          <div class="list-group">
            <p><b>Top 5 Items: Quick Add</b></p>
            <a href="<?php echo $this->url('tracker', array('action' => 'add', 'id' => 14)) ?>" class="addFoodLogItem"><button class = "btn btn-default" type="button">
            <span class="glyphicon glyphicon-plus"></span> 1 Luna Bar</button></a>
            <a href="<?php echo $this->url('tracker', array('action' => 'add', 'id' => 2)) ?>" class="addFoodLogItem"><button class = "btn btn-default" type="button">
            <span class="glyphicon glyphicon-plus"></span> 1 Grande Coffee W Soy and Syrup</button></a>
            <a href="<?php echo $this->url('tracker', array('action' => 'add', 'id' => 3)) ?>" class="addFoodLogItem"><button class = "btn btn-default" type="button"><span class="glyphicon glyphicon-plus"></span> 1 Chobani Flip - Pineapple</button></a>
            <a href="<?php echo $this->url('tracker', array('action' => 'add', 'id' => 4)) ?>" class="addFoodLogItem"><button class = "btn btn-default" type="button">
            <span class="glyphicon glyphicon-plus"></span> 1 Chobani Flip - Almond Coco</button></a>
            <a href="<?php echo $this->url('tracker', array('action' => 'add', 'id' => 5)) ?>" class="addFoodLogItem"><button class = "btn btn-default" type="button">
            <span class="glyphicon glyphicon-plus"></span> 1 Chobani Flip - Key Lime</button></a>
          </div>
          <?php 
                $moodForm->setAttribute('action', $this->url('tracker', array('action' => 'addMood')));
                $moodForm->prepare();
                echo $this->form()->openTag($moodForm);
                echo $this->formCollection($moodForm);
                echo $this->form()->closeTag();
            ?>
            <div id="output">
            </div>
        </div><!--/span-->
</div>

<!-- Daily Log of Items-->
<?php //echo var_dump($today->current()) ?>
<div class="row" id="dailyLogContainer">
<div class="col-md-3">
<div class="panel panel-default">
  <div class="panel-heading"><h4>What Have I Had Today?<h4></div>
<ul>
<?php foreach ($today as $item) : ?>
  <?php echo '<li>'.floor($item->quantity).' '.$item->foodName.'</li>';?>
<?php endforeach; ?>
</ul>
</div>
</div> <!-- column -->

<div class="col-md-3">
<div class="panel panel-default">
  <div class="panel-heading"><h4>Today's Totals<h4></div>
<ul>
<!-- Daily Log of Calories
<?=var_dump($dailyStats)   ?> -->
<?php foreach ($dailyStats as $cat=>$stat) : ?>
  <?php //echo var_dump($drawing) ?>
  
  <?php echo '<li>'.ucfirst($cat).' '.floor($stat).'</li>';?>
<?php endforeach; ?>

</ul>
</div>
</div> <!-- column -->
<div class="col-md-3">
<div class="panel panel-default">
  <div class="panel-heading"><h4>Goals<h4></div>

</div>
</div> <!-- column -->
</div> <!-- Daily Log Container -->


<script src="/js/jquery.form.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>

    

     function updateFoodDataFields(data){
      $('#calories').val(data.calories);
      $('#fat').val(data.fat);
      $('#carbs').val(data.carbs);
      $('#protein').val(data.protein);
      $('#alcohol').val(data.alcohol);
     }

     function nameAlert(){
      if (!($('#nameAlert').length)) {
                        $('#quantity').after('<p id="nameAlert">Food Not found in Database, please enter info below.</p>');
                      }
     }

     function updateOutput(data)
     {
      $('#output').prepend("<p><b>"+ data.mood + "</b> was added to today's mood log!</p>")
                       $('#output').show();
                       $("#output").effect("highlight",{color:"#D8A9DA"},1500);
     }

     /**
     * On Ready...
     */

    $(function() {
        $("#output").hide();


        $('#foodItem .typeahead').typeahead({                          
          name: 'Fooooooood',
          remote: '<?php echo $this->url('tracker',array('action'=>'foodlist',
            'id' => 1))."/%QUERY" ?>'
        });

        //call to add action with food item
        $('#foodItem').on("submit", function(e) {
            e.preventDefault();
            var formurl = '<?php echo $this->url('tracker',array('action'=>'add')) ?>';
            var foodItem = $('input[name=Name]').val();
            
            $.ajax({
            url: formurl,
            type: 'POST',
            ascyn: false,
            dataType: 'json',
            data: $('#foodItem').serialize(),
            success: function(data) {
                       $('#output').prepend("<p><b>"+data.Quantity+" "+data.Name + " added to today's log!</b></p>");
                       $('#output').show();
                       $("#output").effect("highlight",{color:"#D8A9DA"},1500);
                       return false;
                     },
            error: function(data) {
              $('#output').prepend("<p>Unable to add "+foodItem + " to the log</p>");
                       $('#output').show();
                       $("#output").effect("highlight",{color:"#D8A9DA"},1500);
            }
            });

            //clear the form after submitted
            $(this).closest('form').find("input[type=text], textarea").val("");
        });



        $('.addFoodLogItem').on('click', function(e) {
            //e.preventDefault();
            link = $(this).attr('href');
            //alert(link);
            $(this).hide("drop",{direction: "up"},"fast");
            var jqxhr = $.ajax(link)
                  .done(function() {
                    //alert( "success" );
                  })
                  .fail(function() {
                    alert( "error" );
              });
            return false;
        });

        $('#mood').on("submit", function(e) {
            e.preventDefault();
            var formurl = '<?php echo $this->url('tracker',array('action'=>'addMood')) ?>';
            var mood = $('input[name=Mood]').val();

            $.ajax({
            url: formurl,
            type: 'POST',
            ascyn: false,
            dataType: 'json',
            data: $('#mood').serialize(),
            success: function(data) {
                        $('#mood').hide("slow");
                        updateOutput(data);
                        return false;
                     }
            });
        });

        $('#quantity').on("focus", function(e) {
            var formurl = '<?php echo $this->url('tracker',array('action'=>'foodinfo')) ?>';

            $.ajax({
            url: formurl,
            type: 'POST',
            ascyn: false,
            dataType: "json",
            data: $('#foodItem').serialize(),
            success: function(data) {
                      updateFoodDataFields(data);
                      $('.data').show(100);
                       return false;
                     },
            error: function(data) {
                      $('.data').show(100);
                      nameAlert();
                     }
            });
        });
    });
</script>