<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/healthTracker.css') ?>

<?php
$title = 'Login';
$this->headTitle($title);
?>

<h1> <?php echo $this->escapeHtml($title); ?> </h1>
 <?php 

$form->setAttribute('action', $this->url('tracker', array('action' => 'login')));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
